FROM golang:1.20-alpine

ENV GOOGLE_APPLICATION_CREDENTIALS=./configs/sbs-prod-env-firebase.json
ENV ENVIRONMENT=prod
ENV PROD_GCP_CREDS_LOCATION=projects/671861674743/secrets/sbs-prod-config/versions/latest
ENV PROD_DRAFT_SERVER_BASE_URL=https://sbs-drafts-server-w5wydprnbq-uc.a.run.app
ENV PROD_RT_DB_URL=https://sbs-prod-env-default-rtdb.firebaseio.com
# PROD_API_URL will be set after first deployment via: gcloud run services update <service-name> --set-env-vars=PROD_API_URL=<url>
# INFURA_API_KEY should be set via GCP Secret Manager or environment variable
# Set via: gcloud run services update <service-name> --set-env-vars=INFURA_API_KEY=<key>
ENV INFURA_API_KEY=""
# OneSignal SMS (notifications/onesignal). Empty = SMS sends no-op.
# Set via: gcloud run services update <service-name> --set-env-vars=ONESIGNAL_APP_ID=...,ONESIGNAL_REST_API_KEY=...
ENV ONESIGNAL_APP_ID="b7e8d393-68de-4cde-94e3-d013f35a4d25"
ENV ONESIGNAL_REST_API_KEY="oa2qwxvayucyesj4oukpzgsxo"
COPY . /usr/local/go/src/sbs-drafts-api

WORKDIR /usr/local/go/src/sbs-drafts-api

RUN go mod download

RUN go build -o /sbs-drafts-api

COPY ./configs/sbs-prod-env-firebase.json ./configs/sbs-prod-env-firebase.json

EXPOSE 8080

CMD [ "/sbs-drafts-api" ]